[package]
name = "rc-vec-proc_macro"
version = "0.1.0"
edition = "2021"

authors = ["A4-Tacks <wdsjxhno1001@163.com>"]
description = "A proc-macro support crate"
license = "MIT"
repository = "https://github.com/A4-Tacks/rc-vec-rs"

[lib]
proc-macro = true

[dependencies]
