name: Rust test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc
      - run: cargo test --no-fail-fast --all-features
      - run: cargo clippy -- -D warnings

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install miri
        run: rustup component add --toolchain nightly miri
      - run: cargo +nightly miri test --no-fail-fast --all-features
      - run: cargo +nightly miri test --no-fail-fast
